# Generated by Django 5.2.8 on 2025-11-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Новостройка', 'Новостройка'), ('Вторичное жильё', 'Вторичное жильё')], max_length=50, verbose_name='Тип')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('condition', models.CharField(choices=[('С ремонтом', 'С ремонтом'), ('Без ремонта', 'Без ремонта'), ('Среднее состояние', 'Среднее состояние')], max_length=50, verbose_name='Состояние')),
                ('area', models.FloatField(verbose_name='Площадь (м²)')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Цена ($)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('orientation', models.CharField(max_length=255, verbose_name='Ориентир')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('floors_total', models.IntegerField(verbose_name='Всего этажей')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя контакта')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон контакта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Изображение квартиры',
                'verbose_name_plural': 'Изображения квартир',
                'ordering': ['order', 'id'],
            },
        ),
    ]
