# Generated by Django 5.2.8 on 2025-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='district',
            field=models.CharField(choices=[('Мирабадский', 'Мирабадский'), ('Мирзо-Улугбекский', 'Мирзо-Улугбекский'), ('Юнусабадский', 'Юнусабадский'), ('Шайхантохурский', 'Шайхантохурский'), ('Яккасарайский', 'Яккасарайский'), ('Яшнабадский', 'Яшнабадский')], max_length=100, verbose_name='Район'),
        ),
    ]
